// <auto-generated />
namespace Pano.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class ChangeColumnTargetSceneIdFromRequiredToOptionalInSceneHotSpotTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeColumnTargetSceneIdFromRequiredToOptionalInSceneHotSpotTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201911161627452_ChangeColumnTargetSceneIdFromRequiredToOptionalInSceneHotSpotTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
